version: '3.7'
services:
    odoo:
        container_name: odoo17e
        image: bmya/odoo-bmya:l17
        build:
            context:  ./docker/17.0
            dockerfile: Dockerfile
            args:
                ARCH: amd64  # o arm64 amd64
        command: -- -c /etc/odoo/odoo.conf --db-filter=odoo17e_
        restart: always
        networks:
            - default
            - pg14_default
        external_links:
            - db14:db
        ports:
            - "8149:8069"
        volumes:
            - ./data_odoo:/var/lib/odoo:delegated
            - ./odoo:/mnt/odoo:delegated
            - ./enterprise:/mnt/enterprise:delegated
            - ./design-themes:/mnt/design-themes:delegated
            - ./extra-addons:/mnt/extra-addons:delegated
            - ./conf:/etc/odoo
        environment:
            - DB_PORT_5432_TCP_ADDR=db
            - DB_PORT_5432_TCP_PORT=5432
            - DB_ENV_POSTGRES_USER=odoo
            - DB_ENV_POSTGRES_PASSWORD=odoo
            - POSTGRES_DB=postgres

networks:
     default:
         driver: bridge
     pg14_default:
         external: true
